### ISSUE TITLE
Use linear-gradients for RGB color spaces

### ISSUE THREAD

**Issue by tristen** [mapbox/react-colorpickr#115]
Rather than using a background-image that [references a data uri](https://github.com/mapbox/react-colorpickr/blob/61eabde307a0ee88c5b0ed00ff65dbcead1d91dd/example/colorpickr.css#L145-L159)

**Comment by tristen** [comment]
Ahh this is more trouble than its worth. I can get close by stacking gradients but the top level needs transparency for the bottom to show up:

```css
div {
  background:
    linear-gradient(to left bottom, rgba(255,255,255,0.5), rgba(255,0,0,0.5) 80%),
    linear-gradient(to right bottom, rgba(255,255,0,1), rgba(255,0,255,1) 80%);
}
```

Produces:

<img width="368" alt="screen shot 2018-03-13 at 1 47 09 pm" src="https://user-images.githubusercontent.com/61150/37359872-1306b196-26c5-11e8-8a41-a14499c68291.png">

which isn't accurate enough : /
